from __future__ import annotations

import csv
import io
import json
import zipfile
from math import cos, radians, sin
from typing import Sequence
from xml.dom import minidom
from xml.etree import ElementTree as ET

import numpy as np

from .airfoil import airfoil_coordinates, naca4_coordinates
from .models import AirfoilLike, Fluid, WingGeometry
from .wing import WingResult


def airfoil_dat(foil: AirfoilLike, total_points: int = 100) -> str:
    """Export a Selig DAT contour with an exact solver-facing point count."""
    x, y = airfoil_coordinates(foil, total_points=total_points)
    rows = [foil.name]
    rows.extend(f"{xi: .8f}  {yi: .8f}" for xi, yi in zip(x, y))
    return "\n".join(rows) + "\n"


def _allocate_span_panels(lengths: tuple[float, ...], total: int) -> tuple[int, ...]:
    """Allocate an exact panel total while keeping two panels per surface strip."""
    if total < 2 * len(lengths):
        raise ValueError(
            f"Bu geometri için yarı açıklıkta en az {2 * len(lengths)} panel gerekli"
        )
    positive = np.maximum(np.asarray(lengths, dtype=float), 1.0e-12)
    remaining = int(total) - 2 * len(lengths)
    raw = remaining * positive / float(np.sum(positive))
    extra = np.floor(raw).astype(int)
    for index in np.argsort(-(raw - extra))[: remaining - int(np.sum(extra))]:
        extra[index] += 1
    return tuple(int(value) for value in extra + 2)


def _section_foil_tuple(
    foil: AirfoilLike,
    section_foils: Sequence[AirfoilLike] | None,
) -> tuple[AirfoilLike, ...]:
    foils = tuple(section_foils) if section_foils is not None else (foil, foil, foil)
    if len(foils) not in {3, 4}:
        raise ValueError("Kanat için üç ana kesit ve isteğe bağlı bir winglet kesiti gerekli")
    return foils


def flow5_plane_xml(
    foil: AirfoilLike,
    wing: WingGeometry,
    *,
    chordwise_panels: int = 14,
    half_span_panels: int = 18,
    section_foils: Sequence[AirfoilLike] | None = None,
) -> str:
    """Create a flow5 plane XML with an optional high-dihedral winglet strip."""
    if not 4 <= int(chordwise_panels) <= 200:
        raise ValueError("Kord yönündeki panel sayısı 4 ile 200 arasında olmalı")
    if not 4 <= int(half_span_panels) <= 400:
        raise ValueError("Yarı açıklıktaki panel sayısı 4 ile 400 arasında olmalı")
    root = ET.Element("xflplane", {"version": "1.0"})
    units = ET.SubElement(root, "Units")
    for tag, value in (
        ("length_unit_to_meter", "1"),
        ("area_unit_to_m2", "1"),
        ("mass_unit_to_kg", "1"),
        ("speed_unit_to_ms", "1"),
        ("inertia_unit_to_kgm2", "1"),
    ):
        ET.SubElement(units, tag).text = value
    plane = ET.SubElement(root, "Plane")
    ET.SubElement(plane, "Name").text = "AeroOpt optimized wing"
    wing_node = ET.SubElement(plane, "wing")
    ET.SubElement(wing_node, "Name").text = "AeroOpt main wing"
    ET.SubElement(wing_node, "Type").text = "MAINWING"
    color = ET.SubElement(wing_node, "Color")
    for tag, value in (("red", "239"), ("green", "119"), ("blue", "74"), ("alpha", "255")):
        ET.SubElement(color, tag).text = value
    ET.SubElement(wing_node, "Description").text = "Generated by AeroOpt"
    ET.SubElement(wing_node, "Position").text = "0, 0, 0"
    ET.SubElement(wing_node, "Tip_Strips").text = "1"
    ET.SubElement(wing_node, "Rx_angle").text = "0"
    ET.SubElement(wing_node, "Ry_angle").text = "0"
    ET.SubElement(wing_node, "symmetric").text = "true"
    ET.SubElement(wing_node, "Two_Sided").text = "true"
    sections = ET.SubElement(wing_node, "Sections")
    foils = _section_foil_tuple(foil, section_foils)
    if wing.winglet_active:
        if not wing.winglet_geometry_valid:
            raise ValueError("Winglet yatay izdüşümü ana yarı açıklığı tüketiyor")
        strip_panels = _allocate_span_panels(
            (
                wing.main_semispan * wing.mid_span_fraction,
                wing.main_semispan * (1.0 - wing.mid_span_fraction),
                wing.winglet_developed_length,
            ),
            int(half_span_panels),
        )
        winglet_foil = foils[3] if len(foils) == 4 else foils[2]
        section_data = (
            (0.0, wing.root_chord, 0.0, 0.0, 0.0, strip_panels[0], foils[0].name),
            (
                wing.main_semispan * wing.mid_span_fraction,
                wing.mid_chord,
                wing.mid_le_offset,
                0.0,
                wing.effective_mid_twist_deg,
                strip_panels[1],
                foils[1].name,
            ),
            (
                wing.main_semispan,
                wing.winglet_root_chord,
                wing.tip_le_offset,
                wing.winglet_cant_deg,
                wing.tip_twist_deg,
                strip_panels[2],
                winglet_foil.name,
            ),
            (
                wing.main_semispan + wing.winglet_developed_length,
                wing.winglet_tip_chord,
                wing.winglet_tip_le_offset,
                0.0,
                wing.winglet_tip_twist_deg,
                0,
                winglet_foil.name,
            ),
        )
    else:
        strip_panels = _allocate_span_panels(
            (
                wing.main_semispan * wing.mid_span_fraction,
                wing.main_semispan * (1.0 - wing.mid_span_fraction),
            ),
            int(half_span_panels),
        )
        section_data = (
            (0.0, wing.root_chord, 0.0, 0.0, 0.0, strip_panels[0], foils[0].name),
            (
                wing.main_semispan * wing.mid_span_fraction,
                wing.mid_chord,
                wing.mid_le_offset,
                0.0,
                wing.effective_mid_twist_deg,
                strip_panels[1],
                foils[1].name,
            ),
            (
                wing.main_semispan,
                wing.tip_chord,
                wing.tip_le_offset,
                0.0,
                wing.tip_twist_deg,
                0,
                foils[2].name,
            ),
        )
    for y_pos, chord, offset, dihedral, twist, y_panels, foil_name in section_data:
        section = ET.SubElement(sections, "Section")
        values = (
            ("y_position", f"{y_pos:.8g}"),
            ("Chord", f"{chord:.8g}"),
            ("xOffset", f"{offset:.8g}"),
            ("Dihedral", f"{dihedral:.8g}"),
            ("Twist", f"{twist:.8g}"),
            ("x_number_of_panels", str(int(chordwise_panels))),
            ("x_panel_distribution", "COSINE"),
            ("y_number_of_panels", str(y_panels)),
            ("y_panel_distribution", "COSINE"),
            ("Left_Side_FoilName", foil_name),
            ("Right_Side_FoilName", foil_name),
        )
        for tag, value in values:
            ET.SubElement(section, tag).text = value
    raw = ET.tostring(root, encoding="utf-8")
    pretty = minidom.parseString(raw).toprettyxml(indent="  ", encoding="UTF-8").decode("utf-8")
    return pretty.replace("?>", "?>\n<!DOCTYPE flow5>", 1)


def flow5_analysis_xml(
    wing: WingGeometry,
    fluid: Fluid,
    speed_m_s: float,
    method: str,
    *,
    ncrit: float = 9.0,
    xtr_top: float = 1.0,
    xtr_bottom: float = 1.0,
) -> str:
    """Export the final fixed-speed analysis in flow5's documented XML schema."""
    root = ET.Element("xflPlanePolar", {"version": "1.0"})
    units = ET.SubElement(root, "Units")
    for tag, value in (
        ("length_unit_to_meter", "1"),
        ("area_unit_to_m2", "1"),
        ("mass_unit_to_kg", "1"),
        ("speed_unit_to_ms", "1"),
        ("inertia_unit_to_kgm2", "1"),
    ):
        ET.SubElement(units, tag).text = value
    polar = ET.SubElement(root, "Polar")
    ET.SubElement(polar, "Polar_Name").text = f"AeroOpt-{method.upper()}-{speed_m_s:.3f}m_s"
    ET.SubElement(polar, "Plane_Name").text = "AeroOpt optimized wing"
    ET.SubElement(polar, "Type").text = "FIXEDSPEEDPOLAR"
    ET.SubElement(polar, "Method").text = method.upper()
    ET.SubElement(polar, "Include_Fuse_Moments").text = "false"
    ET.SubElement(polar, "Thin_Surfaces").text = "true"
    ET.SubElement(polar, "Ground_Effect").text = "false"
    ET.SubElement(polar, "Ground_Height").text = "0"
    reference = ET.SubElement(polar, "Reference_Dimensions")
    ET.SubElement(reference, "Reference_Dimensions").text = "PROJECTED"
    ET.SubElement(reference, "Reference_Area").text = f"{wing.area:.10g}"
    ET.SubElement(reference, "Reference_Span_Length").text = f"{wing.span:.10g}"
    ET.SubElement(reference, "Reference_Chord_Length").text = f"{wing.mean_aerodynamic_chord:.10g}"
    ET.SubElement(reference, "Include_Other_Wing_Area").text = "false"
    fluid_node = ET.SubElement(polar, "Fluid")
    ET.SubElement(fluid_node, "Viscosity").text = f"{fluid.kinematic_viscosity:.12g}"
    ET.SubElement(fluid_node, "Density").text = f"{fluid.density:.12g}"
    viscous = ET.SubElement(polar, "Viscous_Analysis")
    ET.SubElement(viscous, "Is_Viscous_Analysis").text = "true"
    ET.SubElement(viscous, "From_CL").text = "false"
    transition = ET.SubElement(polar, "XFoil_Settings")
    ET.SubElement(transition, "NCrit").text = f"{ncrit:.8g}"
    ET.SubElement(transition, "Forced_Transition_Top").text = f"{xtr_top:.8g}"
    ET.SubElement(transition, "Forced_Transition_Bottom").text = f"{xtr_bottom:.8g}"
    ET.SubElement(polar, "Fixed_Velocity").text = f"{speed_m_s:.10g}"
    raw = ET.tostring(root, encoding="utf-8")
    pretty = minidom.parseString(raw).toprettyxml(indent="  ", encoding="UTF-8").decode("utf-8")
    return pretty.replace("?>", "?>\n<!DOCTYPE flow5>", 1)


def results_csv(foil: AirfoilLike, result: WingResult) -> str:
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["group", "parameter", "value", "unit"])
    rows = [
        ("airfoil", "name", foil.name, "-"),
        ("airfoil", "max_camber", foil.max_camber, "c"),
        ("airfoil", "camber_position", foil.camber_position, "x/c"),
        ("airfoil", "thickness", foil.thickness, "c"),
        ("wing", "span", result.geometry.span, "m"),
        ("wing", "root_chord", result.geometry.root_chord, "m"),
        ("wing", "tip_chord", result.geometry.tip_chord, "m"),
        ("wing", "mid_chord", result.geometry.mid_chord, "m"),
        ("wing", "taper", result.geometry.taper, "-"),
        ("wing", "quarter_chord_sweep", result.geometry.sweep_deg, "deg"),
        ("wing", "tip_twist", result.geometry.tip_twist_deg, "deg"),
        ("wing", "mid_twist", result.geometry.effective_mid_twist_deg, "deg"),
        ("wing", "incidence", result.geometry.alpha_deg, "deg"),
        ("wing", "area", result.geometry.area, "m2"),
        ("wing", "aspect_ratio", result.geometry.aspect_ratio, "-"),
        ("performance", "CL", result.cl, "-"),
        ("performance", "CD_profile", result.cd_profile, "-"),
        ("performance", "CD_induced", result.cd_induced, "-"),
        ("performance", "CD_total", result.cd_total, "-"),
        ("performance", "lift", result.lift_n, "N"),
        ("performance", "drag", result.drag_n, "N"),
        ("performance", "L_over_D", result.ld, "-"),
        ("performance", "span_efficiency", result.span_efficiency, "-"),
        ("performance", "root_bending_moment", result.root_bending_moment_nm, "N m"),
        ("performance", "stall_ratio", result.stall_ratio, "-"),
    ]
    if result.geometry.winglet_active:
        rows.extend(
            [
                ("winglet", "height", result.geometry.winglet_height, "m"),
                ("winglet", "cant", result.geometry.winglet_cant_deg, "deg"),
                ("winglet", "toe", result.geometry.winglet_toe_deg, "deg"),
                ("winglet", "taper", result.geometry.winglet_taper, "-"),
                ("winglet", "tip_chord", result.geometry.winglet_tip_chord, "m"),
                ("winglet", "surface_area", result.geometry.winglet_surface_area, "m2"),
            ]
        )
    writer.writerows(rows)
    return output.getvalue()


def flow5_native_results_csv(foil: AirfoilLike, result: dict) -> str:
    """CSV export for the flow5-native dictionary result schema."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["group", "parameter", "value", "unit", "source"])
    geometry = result["geometry"]
    rows = [
        ("airfoil", "name", foil.name, "-", "geometry"),
        ("airfoil", "max_camber", foil.max_camber, "c", "geometry"),
        ("airfoil", "camber_position", foil.camber_position, "x/c", "geometry"),
        ("airfoil", "thickness", foil.thickness, "c", "geometry"),
        ("wing", "span", geometry["span"], "m", "geometry"),
        ("wing", "root_chord", geometry["root_chord"], "m", "geometry"),
        ("wing", "tip_chord", geometry["tip_chord"], "m", "geometry"),
        ("wing", "mid_chord", geometry.get("mid_chord", ""), "m", "geometry"),
        ("wing", "taper", geometry["taper"], "-", "geometry"),
        ("wing", "quarter_chord_sweep", geometry["sweep_deg"], "deg", "geometry"),
        ("wing", "tip_twist", geometry["tip_twist_deg"], "deg", "geometry"),
        (
            "wing",
            "mid_twist",
            geometry.get("effective_mid_twist_deg", ""),
            "deg",
            "geometry",
        ),
        ("wing", "incidence", geometry["alpha_deg"], "deg", "flow5"),
        ("wing", "area", geometry["area"], "m2", "geometry"),
        ("wing", "aspect_ratio", geometry["aspect_ratio"], "-", "geometry"),
        ("performance", "CL", result["cl"], "-", "flow5"),
        ("performance", "CD_profile", result["cd_profile"], "-", "flow5"),
        ("performance", "CD_induced", result["cd_induced"], "-", "flow5"),
        ("performance", "CD_total", result["cd_total"], "-", "flow5"),
        ("performance", "lift", result["lift_n"], "N", "flow5"),
        ("performance", "drag", result["drag_n"], "N", "flow5"),
        ("performance", "L_over_D", result["ld"], "-", "flow5"),
        (
            "performance",
            "root_bending_moment",
            result["root_bending_moment_nm"],
            "N m",
            "flow5 telemetry; not a selection condition",
        ),
    ]
    if geometry.get("winglet_active"):
        rows.extend(
            [
                ("winglet", "height", geometry["winglet_height"], "m", "geometry"),
                ("winglet", "cant", geometry["winglet_cant_deg"], "deg", "geometry"),
                ("winglet", "toe", geometry["winglet_toe_deg"], "deg", "geometry"),
                ("winglet", "taper", geometry["winglet_taper"], "-", "geometry"),
                ("winglet", "tip_chord", geometry["winglet_tip_chord"], "m", "geometry"),
                ("winglet", "surface_area", geometry["winglet_surface_area"], "m2", "geometry"),
            ]
        )
    structure = result.get("structural", {})
    if structure.get("enabled"):
        rows.extend(
            [
                ("structure", "passed", structure.get("passed", False), "-", "preliminary beam screen"),
                ("structure", "stress_utilization", structure.get("stress_utilization", ""), "-", "preliminary beam screen"),
                ("structure", "deflection_utilization", structure.get("deflection_utilization", ""), "-", "preliminary beam screen"),
                ("structure", "twist_utilization", structure.get("twist_utilization", ""), "-", "preliminary beam screen"),
                ("structure", "estimated_material_mass", structure.get("estimated_wing_material_mass_kg", ""), "kg", "preliminary beam screen"),
            ]
        )
    hydro = result.get("hydro", {})
    if hydro.get("enabled"):
        rows.extend(
            [
                ("hydro", "cavitation_passed", hydro.get("passed", False), "-", "flow5 Cp_min screen"),
                ("hydro", "constraint_mode", hydro.get("constraint_mode", "hard"), "-", "selection policy"),
                ("hydro", "cavitation_utilization", hydro.get("cavitation_utilization", ""), "-", "flow5 Cp_min screen"),
                ("hydro", "minimum_cavitation_margin", hydro.get("minimum_cavitation_margin_ratio", ""), "-", "flow5 Cp_min screen"),
                ("hydro", "risk_area_percent", hydro.get("risk_area_percent", ""), "%", "flow5 finalist panel map"),
                ("hydro", "physical_onset_area_percent", hydro.get("physical_onset_area_percent", ""), "%", "flow5 finalist panel map"),
                ("hydro", "cavitation_severity_index", hydro.get("cavitation_severity_index", ""), "-", "area-weighted panel screen"),
                ("hydro", "free_surface_risk", hydro.get("free_surface_risk", ""), "-", "Froude/depth screen"),
            ]
        )
    writer.writerows(rows)
    return output.getvalue()


def project_json(payload: dict, result: dict) -> str:
    return json.dumps({"input": payload, "result": result}, ensure_ascii=False, indent=2)


def _wing_foil_contours(
    foil: AirfoilLike,
    *,
    points_per_side: int = 81,
    section_foils: Sequence[AirfoilLike] | None = None,
) -> tuple[np.ndarray, ...]:
    foil_sections = _section_foil_tuple(foil, section_foils)
    contours: list[np.ndarray] = []
    for section_foil in foil_sections:
        contour_x, contour_z = naca4_coordinates(section_foil, points_per_side)
        if np.hypot(contour_x[0] - contour_x[-1], contour_z[0] - contour_z[-1]) < 1e-8:
            contour_x = contour_x[:-1]
            contour_z = contour_z[:-1]
        contours.append(np.column_stack((contour_x, contour_z)))
    if len({len(contour) for contour in contours}) != 1:
        raise ValueError("Kanat kesit profilleri aynı koordinat sayısını kullanmalı")
    return tuple(contours)


def _wing_station_points(
    wing: WingGeometry,
    contours: tuple[np.ndarray, ...],
    *,
    side: int,
    kind: str,
    fraction: float,
) -> np.ndarray:
    if kind == "main":
        chord = wing.chord_at(fraction)
        x_offset = wing.le_offset_at(fraction)
        twist = radians(wing.twist_at(fraction))
        y_center = side * fraction * wing.main_semispan
        z_center = 0.0
        normal_y = 0.0
        normal_z = 1.0
        if fraction <= wing.mid_span_fraction:
            blend = fraction / max(wing.mid_span_fraction, 1.0e-12)
            first, second = contours[0], contours[1]
        else:
            blend = (fraction - wing.mid_span_fraction) / max(
                1.0 - wing.mid_span_fraction, 1.0e-12
            )
            first = contours[1]
            second = contours[3] if wing.winglet_active and len(contours) == 4 else contours[2]
        contour = (1.0 - blend) * first + blend * second
    elif kind == "winglet":
        cant = radians(wing.winglet_cant_deg)
        distance = fraction * wing.winglet_developed_length
        chord = wing.winglet_root_chord + fraction * (
            wing.winglet_tip_chord - wing.winglet_root_chord
        )
        x_offset = wing.tip_le_offset + fraction * (
            wing.winglet_tip_le_offset - wing.tip_le_offset
        )
        twist = radians(wing.tip_twist_deg + fraction * wing.winglet_toe_deg)
        y_center = side * (wing.main_semispan + distance * cos(cant))
        z_center = distance * sin(cant)
        normal_y = -side * sin(cant)
        normal_z = cos(cant)
        contour = contours[3] if len(contours) == 4 else contours[2]
    else:
        raise ValueError(f"Bilinmeyen kanat kesiti: {kind}")

    x_quarter = (contour[:, 0] - 0.25) * chord
    normal_offset = contour[:, 1] * chord
    x_rotated = x_quarter * cos(twist) + normal_offset * sin(twist)
    normal_rotated = -x_quarter * sin(twist) + normal_offset * cos(twist)
    return np.column_stack(
        (
            x_offset + 0.25 * chord + x_rotated,
            y_center + normal_y * normal_rotated,
            z_center + normal_z * normal_rotated,
        )
    )


def wing_step_sections(
    foil: AirfoilLike,
    wing: WingGeometry,
    *,
    points_per_side: int = 81,
    section_foils: Sequence[AirfoilLike] | None = None,
) -> list[list[list[float]]]:
    """Return matched closed section contours for an OpenCascade STEP loft."""
    contours = _wing_foil_contours(
        foil, points_per_side=points_per_side, section_foils=section_foils
    )
    positive_stations: list[tuple[str, float]] = [
        ("main", 0.0),
        ("main", wing.mid_span_fraction),
        ("main", 1.0),
    ]
    if wing.winglet_active:
        if not wing.winglet_geometry_valid:
            raise ValueError("Winglet yatay izdüşümü ana yarı açıklığı tüketiyor")
        positive_stations.append(("winglet", 1.0))
    stations = [
        (-1, kind, fraction) for kind, fraction in reversed(positive_stations[1:])
    ]
    stations.append((1, "main", 0.0))
    stations.extend((1, kind, fraction) for kind, fraction in positive_stations[1:])
    return [
        _wing_station_points(
            wing, contours, side=side, kind=kind, fraction=fraction
        ).astype(float).tolist()
        for side, kind, fraction in stations
    ]


def wing_obj(
    foil: AirfoilLike,
    wing: WingGeometry,
    *,
    span_sections: int = 25,
    points_per_side: int = 81,
    section_foils: Sequence[AirfoilLike] | None = None,
) -> str:
    """Create a connected 3D mesh of the planar wing and optional winglets."""
    if span_sections < 3:
        raise ValueError("OBJ için en az üç açıklık istasyonu gerekli")
    contours = _wing_foil_contours(
        foil, points_per_side=points_per_side, section_foils=section_foils
    )
    section_size = len(contours[0])

    main_half_count = max(3, (span_sections + 1) // 2)
    positive_stations: list[tuple[str, float]] = [
        ("main", float(value)) for value in np.linspace(0.0, 1.0, main_half_count)
    ]
    if wing.winglet_active:
        winglet_count = max(
            3,
            int(
                round(
                    (main_half_count - 1)
                    * wing.winglet_developed_length
                    / max(wing.main_semispan, 1.0e-9)
                )
            )
            + 1,
        )
        positive_stations.extend(
            ("winglet", float(value))
            for value in np.linspace(0.0, 1.0, winglet_count)[1:]
        )
    stations: list[tuple[int, str, float]] = [
        (-1, kind, fraction)
        for kind, fraction in reversed(positive_stations[1:])
    ]
    stations.append((1, "main", 0.0))
    stations.extend((1, kind, fraction) for kind, fraction in positive_stations[1:])

    rows = ["# AeroOpt optimized wing", f"o {foil.name}-wing"]
    for side, kind, fraction in stations:
        points = _wing_station_points(
            wing, contours, side=side, kind=kind, fraction=fraction
        )
        rows.extend(f"v {x:.8f} {y:.8f} {z:.8f}" for x, y, z in points)
    for station in range(len(stations) - 1):
        first = station * section_size + 1
        second = (station + 1) * section_size + 1
        for index in range(section_size):
            following = (index + 1) % section_size
            rows.append(
                f"f {first + index} {second + index} {second + following} {first + following}"
            )
    rows.append("f " + " ".join(str(index) for index in range(section_size, 0, -1)))
    right_start = (len(stations) - 1) * section_size + 1
    rows.append("f " + " ".join(str(right_start + index) for index in range(section_size)))
    return "\n".join(rows) + "\n"


def xfoil_polar_csv(points: list[dict[str, float]]) -> str:
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["alpha_deg", "CL", "CD", "CDp", "Cm_c4", "L_over_D"])
    for point in points:
        writer.writerow(
            [
                point.get("alpha_deg", ""),
                point.get("cl", ""),
                point.get("cd", ""),
                point.get("cdp", ""),
                point.get("cm_c4", ""),
                point.get("cl", 0.0) / max(point.get("cd", 0.0), 1e-12),
            ]
        )
    return output.getvalue()


def flow5_bundle_bytes(
    *,
    foil_dat_text: str,
    plane_xml_text: str,
    wing_obj_text: str,
    results_csv_text: str,
    project_json_text: str,
    polar_csv_text: str | None,
    analysis_xml_text: str | None = None,
    flow5_project_bytes: bytes | None = None,
    wing_step_bytes: bytes | None = None,
    section_foil_dat_texts: Sequence[str] | None = None,
    scalar_only_wing_obj_text: str | None = None,
    scalar_only_wing_step_bytes: bytes | None = None,
    scalar_only_results_csv_text: str | None = None,
    scalar_only_flow5_project_bytes: bytes | None = None,
    scalar_only_same_as_primary: bool | None = None,
) -> bytes:
    """Package the exact foil, 3D wing, plane definition and analysis data together."""
    output = io.BytesIO()
    solved_line = (
        "7. aeropt-optimized.fl5 gerçek flow5 analiz projesidir; flow5 içinde doğrudan açın."
        if flow5_project_bytes
        else "7. Bu pakette çözülmüş .fl5 yoktur; 3B analizi flow5 içinde başlatın."
    )
    step_line = (
        "4. aeropt-wing.step, metre biriminde kapalı OpenCascade loft katısıdır."
        if wing_step_bytes
        else "4. Bu pakette STEP katısı yoktur."
    )
    if scalar_only_same_as_primary is True:
        scalar_line = (
            "8. Fizibilite önceliği kaldırıldığında da aynı kanat seçildi; ayrı dosya çoğaltılmadı."
        )
    elif scalar_only_wing_obj_text and scalar_only_wing_step_bytes:
        scalar_line = (
            "8. aeropt-scalar-only-wing.* dosyaları, fizibilite önceliği olmadan yalnız "
            "skaler toplam amacın seçtiği ayrı kanattır."
        )
    elif scalar_only_same_as_primary is False:
        scalar_line = "8. Skaler-puan alternatifi raporlandı ancak teslim edilebilir CAD çıktısı üretilemedi."
    else:
        scalar_line = ""
    guide = f"""AeroOpt flow5 aktarım paketi

1. aeropt-airfoil.dat profilini içe aktarın.
2. aeropt-wing.xml uçak/kanat tanımını içe aktarın.
3. aeropt-wing.obj, flow5 7.57 içinde 3B geometri kontrolü için kullanılabilir.
{step_line}
5. xfoil-polar.csv varsa polar kaynağını aeropt-project.json içindeki polar_source alanından kontrol edin.
6. aeropt-analysis.xml son flow5 analiz ayarlarını içerir.
{solved_line}
{scalar_line}

Kaynak etiketi flow5 olan sayılar AeroOpt korelasyonundan değil flow5 API çıktısından alınmıştır.
"""
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        archive.writestr("README-flow5.txt", guide)
        archive.writestr("aeropt-airfoil.dat", foil_dat_text)
        if section_foil_dat_texts is not None:
            station_names = ("root", "mid", "tip", "winglet")
            if len(section_foil_dat_texts) not in {3, 4}:
                raise ValueError("Paket için üç veya dört kesit DAT metni gerekli")
            for station, text in zip(station_names, section_foil_dat_texts):
                archive.writestr(f"aeropt-airfoil-{station}.dat", text)
        archive.writestr("aeropt-wing.xml", plane_xml_text)
        archive.writestr("aeropt-wing.obj", wing_obj_text)
        if wing_step_bytes:
            archive.writestr("aeropt-wing.step", wing_step_bytes)
        archive.writestr("aeropt-results.csv", results_csv_text)
        archive.writestr("aeropt-project.json", project_json_text)
        if polar_csv_text:
            archive.writestr("xfoil-polar.csv", polar_csv_text)
        if analysis_xml_text:
            archive.writestr("aeropt-analysis.xml", analysis_xml_text)
        if flow5_project_bytes:
            archive.writestr("aeropt-optimized.fl5", flow5_project_bytes)
        if scalar_only_wing_obj_text:
            archive.writestr("aeropt-scalar-only-wing.obj", scalar_only_wing_obj_text)
        if scalar_only_wing_step_bytes:
            archive.writestr("aeropt-scalar-only-wing.step", scalar_only_wing_step_bytes)
        if scalar_only_results_csv_text:
            archive.writestr("aeropt-scalar-only-results.csv", scalar_only_results_csv_text)
        if scalar_only_flow5_project_bytes:
            archive.writestr(
                "aeropt-scalar-only-optimized.fl5",
                scalar_only_flow5_project_bytes,
            )
    return output.getvalue()
